#reference: https://www.youtube.com/watch?v=5N6gTVCG_rw
version: "3"

networks:
  yii:

services:

#server
  nginx:
    image: nginx:stable-alpine
    container_name: yii_nginx
    ports:
      - "8088:80"
      - "8089:81"
    volumes:
      - ./src:/var/www/html
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgresql
      - redis
    networks:
      - yii

  #for complex web application (preferred)
  #database
  postgresql:
    image: postgres:alpine
    container_name: yii_postgresql
    restart: unless-stopped
    ports:
      - "6432:5432"
    tty: true
    volumes:
      - ./docker/postgresql:/var/lib/postgresql
    environment: #change your environment here
      POSTGRES_DB: db_test
      POSTGRES_USER: seeker
      POSTGRES_PASSWORD: seeker
      SERVICE_TAGS: dev
      SERVICE_NAME: postgresql
    networks:
      - yii

#language
  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: yii_php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9090:9000"
    networks:
      - yii

#cache
  redis:
    image: redis:alpine
    container_name: yii_redis
    restart: unless-stopped
    ports:
      - "7379:6379"
    networks:
      - yii
